import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono, Amarante } from "next/font/google";
import "./globals.css";

const amarante = Amarante({ 
  weight: '400', 
  subsets: ['latin'],
  variable: '--font-amarante' 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amarante.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Load AdSense Script Globally */}
        <Script
          id="adsbygoogle-init"
          async
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID}`}
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        
        {children}
      </body>
    </html>
  );
}
